package me.qianyue.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONTACT.
 */
public class Contact {

    private Long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String number;
    private Double numbertwo;
    /** Not-null value. */
    private String photoPath;
    private java.util.Date date;

    public Contact() {
    }

    public Contact(Long id) {
        this.id = id;
    }

    public Contact(Long id, String name, String number, Double numbertwo, String photoPath, java.util.Date date) {
        this.id = id;
        this.name = name;
        this.number = number;
        this.numbertwo = numbertwo;
        this.photoPath = photoPath;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getNumber() {
        return number;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNumber(String number) {
        this.number = number;
    }

    public Double getNumbertwo() {
        return numbertwo;
    }

    public void setNumbertwo(Double numbertwo) {
        this.numbertwo = numbertwo;
    }

    /** Not-null value. */
    public String getPhotoPath() {
        return photoPath;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPhotoPath(String photoPath) {
        this.photoPath = photoPath;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
