package me.qianyue.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONTACT.
 */
public class Contact {

    private Long id;
    /** Not-null value. */
    private String name;
    private int number;
    /** Not-null value. */
    private String photoPath;

    public Contact() {
    }

    public Contact(Long id) {
        this.id = id;
    }

    public Contact(Long id, String name, int number, String photoPath) {
        this.id = id;
        this.name = name;
        this.number = number;
        this.photoPath = photoPath;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public int getNumber() {
        return number;
    }

    public void setNumber(int number) {
        this.number = number;
    }

    /** Not-null value. */
    public String getPhotoPath() {
        return photoPath;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPhotoPath(String photoPath) {
        this.photoPath = photoPath;
    }

}
